export const Types ={
  FETCHING_MEALS: 'FETCHING_MEALS',
  FETCHED_MEALS: 'FETCHED_MEALS',
  ADD_TO_BASKET: 'ADD_TO_BASKET',
  REMOVE_FROM_BASKET: 'REMOVE_FROM_BASKET',
  FETCHING_CATEGORIES: 'FETCHING_CATEGORIES',
  FETCHED_CATEGORIES: 'FETCHED_CATEGORIES',
}